/**
 * Seed catalogue: hand-picked production websites (2024-2026) spanning
 * industries, design moods, and macrostructures. Editorial
 * choices, not exhaustive.
 *
 * Curation rule: the bar is "would a designer building a brief pause
 * here?", not "is this a popular brand?". Prefer intentional design
 * over loud marketing.
 *
 * Run: `pnpm capture:seed --go --publish --skip-existing` after edits.
 * Failures are reported in the per-run JSON; prune them out after.
 */

export type SeedUrl = {
  url: string;
  /** Optional override slug (otherwise derived from host). */
  slug?: string;
  /** One-liner that helps when reviewing the resulting capture. */
  note?: string;
};

export const seedUrls: SeedUrl[] = [
  /* ─────────────── Dev tools / runtimes / IDEs ─────────────── */
  { url: "https://linear.app", note: "Issue tracking; dark editorial." },
  { url: "https://vercel.com", note: "Frontend cloud; pure-black, type-led." },
  { url: "https://supabase.com", note: "Backend; bento heavy." },
  { url: "https://neon.tech", note: "Postgres; technical/almanac." },
  { url: "https://railway.com", note: "Infra; brutalist accent on dark." },
  { url: "https://www.cloudflare.com", note: "Edge platform; dense home." },
  { url: "https://modal.com", note: "Compute; technical/midnight." },
  { url: "https://replicate.com", note: "AI hosting; bento-led." },
  { url: "https://attio.com", note: "CRM; soft/salon." },
  { url: "https://www.raycast.com", note: "Launcher; component-playground." },
  { url: "https://arc.net", note: "Browser; portrait-of-product." },
  { url: "https://granola.ai", note: "AI notes; minimal, soft." },
  { url: "https://resend.com", note: "Email API; dark + technical." },
  { url: "https://n8n.io", note: "Workflow automation; dense bento." },
  { url: "https://www.val.town", note: "Cloud functions; loud, brutal." },
  { url: "https://bun.com", note: "JS runtime; dark, dense." },
  { url: "https://deno.com", note: "JS runtime; technical/almanac." },
  { url: "https://htmx.org", note: "Frontend lib; brutalist + technical." },
  { url: "https://biomejs.dev", note: "JS toolchain; minimal." },
  { url: "https://www.cursor.com", note: "AI IDE; bento + dark." },
  { url: "https://zed.dev", note: "Code editor; bold dark hero." },
  { url: "https://www.warp.dev", note: "Terminal; dark technical." },
  { url: "https://gitbutler.com", note: "Git client; muted, soft." },
  { url: "https://graphite.dev", note: "Code review; clean technical." },
  { url: "https://posthog.com", note: "Analytics; bold, playful." },
  { url: "https://sentry.io", note: "Observability; dark, dense." },
  { url: "https://liveblocks.io", note: "Realtime; soft palette." },
  { url: "https://e2b.dev", note: "Sandbox runtime; technical." },
  { url: "https://www.cleanshot.com", note: "Screenshot tool; product-focused." },
  { url: "https://convex.dev", note: "Realtime DB; bento + soft." },
  { url: "https://turso.tech", note: "Edge SQLite; technical." },
  { url: "https://www.inngest.com", note: "Workflow durable jobs." },
  { url: "https://trigger.dev", note: "Background jobs; bento." },
  { url: "https://workos.com", note: "Auth/SSO; clean enterprise." },
  { url: "https://clerk.com", note: "Auth; gradient hero." },
  { url: "https://www.tinybird.co", note: "Realtime data; dark." },
  { url: "https://highlight.io", note: "Session replay; dark technical." },
  { url: "https://www.knock.app", note: "Notifications infra." },
  { url: "https://www.svix.com", note: "Webhooks; clean technical." },
  { url: "https://dub.co", note: "Link shortener; modern dark." },
  { url: "https://www.loops.so", note: "Email for SaaS; soft." },
  { url: "https://plain.com", note: "Customer support; calm." },
  { url: "https://www.tldraw.com", note: "Whiteboard; component-playground." },
  { url: "https://excalidraw.com", note: "Sketching; workbench." },
  { url: "https://www.framer.com", note: "Design tool; component-playground." },
  { url: "https://www.figma.com", note: "Design tool; bento." },
  { url: "https://www.notion.com", note: "Productivity; soft FAQ." },
  { url: "https://www.craft.do", note: "Notes; soft, photographic." },
  { url: "https://www.tana.inc", note: "Knowledge base; dark technical." },
  { url: "https://www.reflect.app", note: "Notes; soft + warm." },
  { url: "https://height.app", note: "Project mgmt; clean." },
  { url: "https://magicui.design", note: "Component library; component-playground." },
  { url: "https://ui.shadcn.com", note: "Component library; technical/almanac." },
  { url: "https://once.tools", note: "Tools index; index-first." },
  { url: "https://stately.ai", note: "State machines; technical." },
  { url: "https://www.builder.io", note: "Visual builder." },
  { url: "https://railway.app", note: "Infra; same as railway.com." },
  { url: "https://render.com", note: "Hosting; clean technical." },
  { url: "https://fly.io", note: "Edge VMs; dark technical." },
  { url: "https://www.koyeb.com", note: "Edge hosting." },
  { url: "https://uploadcare.com", note: "Media CDN." },
  { url: "https://www.bunny.net", note: "CDN; bold." },
  { url: "https://www.algolia.com", note: "Search SaaS; clean." },
  { url: "https://meilisearch.com", note: "Open search; bento." },
  { url: "https://typesense.org", note: "Open search; technical." },
  { url: "https://www.elastic.co", note: "Search/observability." },
  { url: "https://www.datadoghq.com", note: "Monitoring; dense." },
  { url: "https://grafana.com", note: "Dashboards; technical." },
  { url: "https://www.warp.dev", note: "Terminal; same as above." },
  { url: "https://www.polypane.app", note: "Browser for devs; soft." },
  { url: "https://www.poly.app", note: "Design tool; eh check." },
  { url: "https://www.spline.design", note: "3D design; gradient hero." },
  { url: "https://rive.app", note: "Animation; bento." },
  { url: "https://lottiefiles.com", note: "Animation library." },

  /* ─────────────── AI labs / consumer / inference ─────────────── */
  { url: "https://www.anthropic.com", note: "AI lab; editorial newsprint." },
  { url: "https://openai.com", note: "AI lab; clean swiss." },
  { url: "https://mistral.ai", note: "AI lab; technical/almanac." },
  { url: "https://www.perplexity.ai", note: "AI search; bento dark." },
  { url: "https://runwayml.com", note: "Creative AI; photographic." },
  { url: "https://www.together.ai", note: "Open inference platform." },
  { url: "https://huggingface.co", note: "Model hub; bento." },
  { url: "https://groq.com", note: "Fast inference; technical." },
  { url: "https://www.fal.ai", note: "Generative; bold dark." },
  { url: "https://elevenlabs.io", note: "Voice AI; bento dark." },
  { url: "https://suno.com", note: "Music AI; dark + brand." },
  { url: "https://www.midjourney.com", note: "Image AI; mood-led." },
  { url: "https://pika.art", note: "Video AI; gradient." },
  { url: "https://claude.ai", note: "AI assistant product." },
  { url: "https://www.pi.ai", note: "AI assistant; soft." },
  { url: "https://character.ai", note: "AI characters; loud." },
  { url: "https://lovable.dev", note: "AI builder; bento." },
  { url: "https://v0.dev", note: "AI UI gen; dark + bento." },
  { url: "https://bolt.new", note: "AI builder; bold." },
  { url: "https://devin.ai", note: "AI engineer; technical." },
  { url: "https://cognition.ai", note: "AI lab; minimal manifesto." },
  { url: "https://www.dust.tt", note: "AI workspace; soft." },
  { url: "https://factory.ai", note: "AI engineering; dark." },
  { url: "https://cohere.com", note: "Enterprise LLMs; clean." },
  { url: "https://www.langchain.com", note: "LLM frameworks; technical." },
  { url: "https://www.llamaindex.ai", note: "RAG framework; technical." },
  { url: "https://www.pinecone.io", note: "Vector DB; technical." },
  { url: "https://weaviate.io", note: "Vector DB; bento." },
  { url: "https://www.qdrant.tech", note: "Vector DB; dark." },
  { url: "https://www.trychroma.com", note: "Embeddings DB; minimal." },
  { url: "https://crew.ai", note: "Agent framework." },
  { url: "https://www.langfuse.com", note: "LLM ops; technical." },
  { url: "https://lmstudio.ai", note: "Local LLM; minimal." },
  { url: "https://ollama.com", note: "Local LLM; minimal." },
  { url: "https://www.scale.com", note: "AI data labeling." },
  { url: "https://www.adept.ai", note: "AI agents; minimal." },
  { url: "https://www.heygen.com", note: "AI avatars." },
  { url: "https://www.synthesia.io", note: "AI video; product-led." },
  { url: "https://www.descript.com", note: "AI editing; loud + bento." },
  { url: "https://www.captions.ai", note: "AI captions; bold." },
  { url: "https://www.anchor.fm", note: "Podcast tool." },
  { url: "https://www.kapwing.com", note: "Video editor; bento." },
  { url: "https://blackforestlabs.ai", note: "Image AI lab; minimal." },
  { url: "https://stability.ai", note: "Image AI; dark." },
  { url: "https://lumalabs.ai", note: "3D AI; dark photographic." },

  /* ─────────────── Fintech / banking / spend ─────────────── */
  { url: "https://mercury.com", note: "Banking; quote-led + soft." },
  { url: "https://ramp.com", note: "Spend; stat-led." },
  { url: "https://stripe.com", note: "Payments; gradient hero." },
  { url: "https://monzo.com", note: "Bank; loud + photographic." },
  { url: "https://www.brex.com", note: "Spend; technical/midnight." },
  { url: "https://www.revolut.com", note: "Bank; loud." },
  { url: "https://wise.com", note: "Money transfer; clean." },
  { url: "https://plaid.com", note: "Fintech infra; clean." },
  { url: "https://www.moderntreasury.com", note: "Payments infra; soft." },
  { url: "https://www.alloy.com", note: "Identity verification." },
  { url: "https://stash.com", note: "Investing; calm." },
  { url: "https://www.public.com", note: "Investing; minimal." },
  { url: "https://wealthfront.com", note: "Investing; clean." },
  { url: "https://www.lemonade.com", note: "Insurance; loud + photographic." },
  { url: "https://www.chime.com", note: "Bank; soft." },
  { url: "https://copilot.money", note: "Personal finance; soft warm." },
  { url: "https://onecard.co.in", note: "Card; eh check." },
  { url: "https://www.wagmi.com", note: "Web3 dev tools; dark." },
  { url: "https://www.coinbase.com", note: "Crypto; clean." },
  { url: "https://www.kraken.com", note: "Crypto exchange." },
  { url: "https://blockstream.com", note: "Bitcoin infra; minimal." },

  /* ─────────────── Agencies / studios ─────────────── */
  { url: "https://locomotive.ca", note: "Agency; specimen + scroll." },
  { url: "https://hellomonday.com", note: "Agency; portfolio grid." },
  { url: "https://studio.design", note: "Studio; portfolio grid." },
  { url: "https://www.merci-michel.com", note: "Studio; photographic." },
  { url: "https://www.work.co", note: "Work & Co; clean studio." },
  { url: "https://www.collins.is", note: "Brand studio; bold typography." },
  { url: "https://pentagram.com", note: "Pentagram; classic specimen." },
  { url: "https://area17.com", note: "Area 17; portfolio grid." },
  { url: "https://instrument.com", note: "Instrument; bento + dark." },
  { url: "https://www.antinomy.studio", note: "Brand studio; manifesto." },
  { url: "https://2x4.org", note: "2x4; specimen." },
  { url: "https://akufen.ca", note: "Akufen; agency." },
  { url: "https://www.dia.tv", note: "Dia; brand + motion." },
  { url: "https://stinkstudios.com", note: "Stink Studios; agency." },
  { url: "https://activetheory.net", note: "Active Theory; experimental." },
  { url: "https://resn.co.nz", note: "RESN; experimental." },
  { url: "https://buck.co", note: "Buck; animation." },
  { url: "https://www.northkingdom.com", note: "North Kingdom." },
  { url: "https://www.studiometa.fr", note: "Studio Meta." },
  { url: "https://www.studiopolygon.com", note: "Polygon; eh check." },
  { url: "https://obys.agency", note: "Obys Agency." },
  { url: "https://lusion.co", note: "Lusion; experimental WebGL." },
  { url: "https://igloo.inc", note: "Igloo; eh check." },
  { url: "https://www.unfold.no", note: "Unfold; brand." },
  { url: "https://www.upperquad.com", note: "Upperquad." },
  { url: "https://www.locomotive.ca", note: "Locomotive (dup)." },
  { url: "https://www.basicagency.com", note: "Basic Agency." },
  { url: "https://method.com", note: "Method." },
  { url: "https://moodelier.com", note: "Moodelier." },
  { url: "https://www.mubien.com", note: "Mubien; eh check." },
  { url: "https://www.gretel.com", note: "Gretel; brand studio." },
  { url: "https://designstudio.com", note: "DesignStudio." },
  { url: "https://www.frame.io", note: "Frame.io; product+brand." },
  { url: "https://www.studio-output.com", note: "Studio Output." },
  { url: "https://nbstudio.co.uk", note: "NB Studio; UK brand." },
  { url: "https://www.dn-co.com", note: "dn&co; UK brand." },
  { url: "https://www.spincreative.com", note: "Spin Creative." },
  { url: "https://lateral.studio", note: "Lateral Studio." },
  { url: "https://www.signstudio.com", note: "Sign Studio." },
  { url: "https://outpost.com", note: "Outpost; eh check." },
  { url: "https://lift.studio", note: "Lift Studio." },
  { url: "https://standardvision.com", note: "Standard Vision." },
  { url: "https://www.pentagram.com", note: "Pentagram (dup)." },
  { url: "https://www.elastique.com", note: "Élastique." },

  /* ─────────────── Designer / dev portfolios ─────────────── */
  { url: "https://www.robin-noguier.com", note: "Robin Noguier; portfolio." },
  { url: "https://www.vanschneider.com", note: "Tobias van Schneider." },
  { url: "https://daniel.do", note: "Daniel; long-document." },
  { url: "https://rauno.me", note: "Rauno Freiberg." },
  { url: "https://emilkowal.ski", note: "Emil Kowalski; animations." },
  { url: "https://paco.me", note: "Paco; minimal." },
  { url: "https://tobiasahlin.com", note: "Tobias Ahlin." },
  { url: "https://lynnandtonic.com", note: "Lynn Fisher." },
  { url: "https://read.cv", note: "Read.cv; CV platform." },
  { url: "https://leerob.com", note: "Lee Robinson." },
  { url: "https://luca.computer", note: "Luca Pellegrini." },
  { url: "https://www.kkga.me", note: "Aleksandr Yakunichev." },
  { url: "https://www.shadcn.com", note: "shadcn." },
  { url: "https://www.craigmod.com", note: "Craig Mod; long-form." },
  { url: "https://wesbos.com", note: "Wes Bos." },
  { url: "https://overreacted.io", note: "Dan Abramov; minimal blog." },
  { url: "https://danabra.mov", note: "Dan Abramov; vanity." },
  { url: "https://www.joshwcomeau.com", note: "Josh Comeau." },
  { url: "https://csswizardry.com", note: "Harry Roberts." },
  { url: "https://piccalil.li", note: "Andy Bell." },
  { url: "https://jhey.dev", note: "Jhey Tompkins." },
  { url: "https://nerdy.dev", note: "Adam Argyle." },
  { url: "https://bruno-simon.com", note: "Bruno Simon; 3D portfolio." },
  { url: "https://maggieappleton.com", note: "Maggie Appleton." },
  { url: "https://samwho.dev", note: "Sam Rose; interactive." },
  { url: "https://andy.works", note: "Andy Allen." },
  { url: "https://aristidebenoist.com", note: "Aristide Benoist; experimental." },
  { url: "https://www.julian.com", note: "Julian Shapiro; writing." },
  { url: "https://yuanchuan.dev", note: "Yuanchuan Cao; CSS art." },
  { url: "https://www.ryanlefevre.com", note: "Ryan Lefevre." },
  { url: "https://swyx.io", note: "Shawn Wang." },
  { url: "https://addyosmani.com", note: "Addy Osmani." },
  { url: "https://www.smashingmagazine.com", note: "Smashing." },
  { url: "https://romainavalle.com", note: "Romain Avalle." },
  { url: "https://qjwang.com", note: "Q Wang." },
  { url: "https://www.davidhuh.com", note: "David Huh." },
  { url: "https://etienne.studio", note: "Etienne Godiard; eh check." },
  { url: "https://anthonyhobday.com", note: "Anthony Hobday; design rules." },
  { url: "https://www.jamesbosworth.com", note: "James Bosworth." },
  { url: "https://frankchimero.com", note: "Frank Chimero." },
  { url: "https://www.designbetter.co", note: "DesignBetter (InVision)." },
  { url: "https://benji.org", note: "Benjamin Lazar." },
  { url: "https://www.studio-in.ch", note: "Studio.IN." },
  { url: "https://noahkalina.com", note: "Noah Kalina; photographer." },

  /* ─────────────── Type foundries ─────────────── */
  { url: "https://ohnotype.co", note: "OH no Type Co." },
  { url: "https://klim.co.nz", note: "Klim Type Foundry." },
  { url: "https://www.typotheque.com", note: "Typotheque." },
  { url: "https://www.fontshare.com", note: "Fontshare; free fonts." },
  { url: "https://commercialtype.com", note: "Commercial Type." },
  { url: "https://abcdinamo.com", note: "ABC Dinamo." },
  { url: "https://displaay.net", note: "Displaay Type." },
  { url: "https://pangrampangram.com", note: "Pangram Pangram." },
  { url: "https://www.205.tf", note: "205TF." },
  { url: "https://www.welcometo.as", note: "Welcome To.as." },
  { url: "https://www.lineto.com", note: "Lineto." },
  { url: "https://www.ourtype.com", note: "OurType." },
  { url: "https://www.boldmonday.com", note: "Bold Monday." },
  { url: "https://www.ortype.is", note: "Or Type." },
  { url: "https://lettersfromsweden.se", note: "Letters from Sweden." },
  { url: "https://www.frerejones.com", note: "Frere-Jones Type." },
  { url: "https://www.houseindustries.com", note: "House Industries." },
  { url: "https://standardtype.com", note: "Standard Type." },
  { url: "https://www.typotheque.com", note: "Typotheque (dup)." },
  { url: "https://www.fontsmith.com", note: "Fontsmith." },
  { url: "https://www.grillitype.com", note: "Grilli Type / GT." },
  { url: "https://www.charlesnix.com", note: "Charles Nix." },
  { url: "https://www.fontwerk.com", note: "Fontwerk." },
  { url: "https://www.alphabettype.com", note: "Alphabet Type." },
  { url: "https://velvetyne.fr", note: "Velvetyne free fonts." },
  { url: "https://open-foundry.com", note: "Open Foundry." },
  { url: "https://www.typeroom.eu", note: "TypeRoom." },
  { url: "https://www.fontsinuse.com", note: "Fonts In Use." },
  { url: "https://justanotherfoundry.com", note: "Just Another Foundry." },
  { url: "https://thedesignersfoundry.com", note: "The Designers Foundry." },
  { url: "https://camelot-typefaces.com", note: "Camelot Typefaces." },
  { url: "https://www.rosettatype.com", note: "Rosetta Type." },
  { url: "https://emigre.com", note: "Emigre." },

  /* ─────────────── Editorial / culture / journalism ─────────────── */
  { url: "https://www.are.na", note: "Are.na; editorial newsprint." },
  { url: "https://mubi.com", note: "MUBI; cinema." },
  { url: "https://a24films.com", note: "A24; photographic." },
  { url: "https://www.itsnicethat.com", note: "It's Nice That; long-document." },
  { url: "https://thecreativeindependent.com", note: "The Creative Independent." },
  { url: "https://works.studio", note: "Works Studio; specimen." },
  { url: "https://www.frieze.com", note: "Frieze magazine." },
  { url: "https://www.e-flux.com", note: "e-flux; criticism." },
  { url: "https://kottke.org", note: "Kottke; classic blog." },
  { url: "https://daringfireball.net", note: "Daring Fireball; minimal blog." },
  { url: "https://longreads.com", note: "Longreads." },
  { url: "https://www.aperture.org", note: "Aperture; photography." },
  { url: "https://www.artforum.com", note: "Artforum." },
  { url: "https://www.wired.com", note: "Wired." },
  { url: "https://www.theverge.com", note: "The Verge." },
  { url: "https://pitchfork.com", note: "Pitchfork." },
  { url: "https://www.residentadvisor.net", note: "Resident Advisor." },
  { url: "https://www.thequietus.com", note: "The Quietus." },
  { url: "https://hypebeast.com", note: "Hypebeast." },
  { url: "https://hypebeast.kr", note: "Hypebeast KR." },
  { url: "https://www.highsnobiety.com", note: "Highsnobiety." },
  { url: "https://www.dezeen.com", note: "Dezeen; architecture." },
  { url: "https://www.archdaily.com", note: "ArchDaily." },
  { url: "https://www.wallpaper.com", note: "Wallpaper magazine." },
  { url: "https://www.domusweb.it", note: "Domus." },
  { url: "https://www.frame.com", note: "Frame magazine." },
  { url: "https://www.bloomberg.com/graphics", note: "Bloomberg graphics." },
  { url: "https://pudding.cool", note: "The Pudding; data viz." },
  { url: "https://fivethirtyeight.com", note: "FiveThirtyEight." },
  { url: "https://www.themarshallproject.org", note: "The Marshall Project." },
  { url: "https://qz.com", note: "Quartz." },
  { url: "https://www.nytimes.com/section/style", note: "NYT Style." },
  { url: "https://www.theatlantic.com", note: "The Atlantic." },
  { url: "https://www.realreviewmag.com", note: "Real Review architecture." },
  { url: "https://www.apartamentomagazine.com", note: "Apartamento." },
  { url: "https://magazine-b.com", note: "MAGAZINE B; brand stories." },
  { url: "https://www.idea-mag.com", note: "IDEA magazine; Japan." },
  { url: "https://www.eyemagazine.com", note: "Eye magazine." },
  { url: "https://www.creativereview.co.uk", note: "Creative Review." },
  { url: "https://www.fastcompany.com", note: "Fast Company." },
  { url: "https://aeon.co", note: "Aeon; long-form." },
  { url: "https://psyche.co", note: "Psyche; long-form." },
  { url: "https://knowablemagazine.org", note: "Knowable." },
  { url: "https://www.bittersoutherner.com", note: "Bitter Southerner; editorial." },
  { url: "https://www.vox.com", note: "Vox." },
  { url: "https://restofworld.org", note: "Rest of World." },
  { url: "https://thecorrespondent.com", note: "The Correspondent." },
  { url: "https://www.huckmag.com", note: "Huck magazine." },
  { url: "https://crackmagazine.net", note: "Crack magazine." },

  /* ─────────────── Music labels / streaming ─────────────── */
  { url: "https://www.4ad.com", note: "4AD records." },
  { url: "https://warp.net", note: "Warp records." },
  { url: "https://ninjatune.net", note: "Ninja Tune." },
  { url: "https://xlrecordings.com", note: "XL Recordings." },
  { url: "https://ghostly.com", note: "Ghostly International." },
  { url: "https://www.subpop.com", note: "Sub Pop." },
  { url: "https://stonesthrow.com", note: "Stones Throw." },
  { url: "https://www.kompakt.fm", note: "Kompakt." },
  { url: "https://moshimoshimusic.com", note: "Moshi Moshi." },
  { url: "https://factmag.com", note: "FACT magazine." },
  { url: "https://bandcamp.com", note: "Bandcamp." },
  { url: "https://soundcloud.com", note: "SoundCloud." },
  { url: "https://anchor.fm", note: "Anchor (dup)." },
  { url: "https://www.spotify.com", note: "Spotify." },
  { url: "https://www.apple.com/apple-music", note: "Apple Music page." },
  { url: "https://tidal.com", note: "Tidal." },
  { url: "https://www.deezer.com", note: "Deezer." },
  { url: "https://www.dolby.com/atmos", note: "Dolby Atmos." },

  /* ─────────────── Cinema / streaming / TV ─────────────── */
  { url: "https://www.criterion.com", note: "Criterion Collection." },
  { url: "https://www.netflix.com", note: "Netflix." },
  { url: "https://tv.apple.com", note: "Apple TV+." },
  { url: "https://www.hbo.com", note: "HBO." },
  { url: "https://www.disneyplus.com", note: "Disney+." },
  { url: "https://www.dropout.tv", note: "Dropout." },
  { url: "https://nebula.tv", note: "Nebula." },
  { url: "https://www.curiositystream.com", note: "Curiosity Stream." },

  /* ─────────────── E-commerce / D2C / lifestyle ─────────────── */
  { url: "https://www.aesop.com", note: "Aesop; soft + warm." },
  { url: "https://buly1803.com", note: "Buly 1803." },
  { url: "https://www.snowpeak.com", note: "Snow Peak." },
  { url: "https://www.freitag.ch", note: "Freitag bags." },
  { url: "https://www.patagonia.com", note: "Patagonia." },
  { url: "https://www.allbirds.com", note: "Allbirds." },
  { url: "https://www.everlane.com", note: "Everlane." },
  { url: "https://www.cuyana.com", note: "Cuyana." },
  { url: "https://www.glossier.com", note: "Glossier." },
  { url: "https://drunkelephant.com", note: "Drunk Elephant." },
  { url: "https://augustinusbader.com", note: "Augustinus Bader." },
  { url: "https://www.maharishistore.com", note: "Maharishi." },
  { url: "https://www.acnestudios.com", note: "Acne Studios." },
  { url: "https://www.hodinkee.com", note: "Hodinkee watches." },
  { url: "https://www.ssense.com", note: "SSENSE." },
  { url: "https://www.mrporter.com", note: "MR PORTER." },
  { url: "https://www.net-a-porter.com", note: "Net-a-Porter." },
  { url: "https://www.thefutur.com", note: "The Futur." },
  { url: "https://www.norseprojects.com", note: "Norse Projects." },
  { url: "https://www.aimeleondore.com", note: "Aimé Leon Dore." },
  { url: "https://www.stussy.com", note: "Stüssy." },
  { url: "https://www.kith.com", note: "Kith." },
  { url: "https://www.thereformation.com", note: "Reformation." },
  { url: "https://shop.lululemon.com", note: "Lululemon." },
  { url: "https://www.outdoorvoices.com", note: "Outdoor Voices." },
  { url: "https://www.casetify.com", note: "Casetify." },
  { url: "https://www.warbyparker.com", note: "Warby Parker." },
  { url: "https://www.hellofresh.com", note: "HelloFresh." },
  { url: "https://www.blueapron.com", note: "Blue Apron." },
  { url: "https://www.casper.com", note: "Casper." },
  { url: "https://www.dyson.com", note: "Dyson; product pages." },
  { url: "https://www.bang-olufsen.com", note: "Bang & Olufsen." },
  { url: "https://www.bose.com", note: "Bose." },
  { url: "https://www.sonos.com", note: "Sonos." },
  { url: "https://www.bowerswilkins.com", note: "B&W audio." },
  { url: "https://www.kefdirect.com", note: "KEF audio." },
  { url: "https://www.master-dynamic.com", note: "Master & Dynamic." },
  { url: "https://www.hem.com", note: "Hem furniture." },
  { url: "https://www.fermliving.com", note: "Ferm Living." },
  { url: "https://www.muuto.com", note: "Muuto." },
  { url: "https://artek.fi", note: "Artek." },
  { url: "https://www.vitra.com", note: "Vitra." },
  { url: "https://www.hermanmiller.com", note: "Herman Miller." },
  { url: "https://www.knoll.com", note: "Knoll." },
  { url: "https://www.tomdixon.net", note: "Tom Dixon." },
  { url: "https://www.flos.com", note: "Flos lighting." },
  { url: "https://www.louispoulsen.com", note: "Louis Poulsen." },
  { url: "https://www.menuworld.com", note: "Menu / Audo." },
  { url: "https://www.audocph.com", note: "Audo Copenhagen." },
  { url: "https://www.normarchitects.com", note: "Norm Architects." },
  { url: "https://www.maharam.com", note: "Maharam textiles." },
  { url: "https://www.kvadrat.dk", note: "Kvadrat textiles." },
  { url: "https://www.heathceramics.com", note: "Heath Ceramics." },
  { url: "https://www.fjallraven.com", note: "Fjällräven." },
  { url: "https://www.arcteryx.com", note: "Arc'teryx." },
  { url: "https://www.canadagoose.com", note: "Canada Goose." },
  { url: "https://www.norrona.com", note: "Norrøna." },
  { url: "https://www.peakdesign.com", note: "Peak Design." },
  { url: "https://www.goal-zero.com", note: "Goal Zero." },
  { url: "https://www.trayvax.com", note: "Trayvax." },
  { url: "https://www.bellroy.com", note: "Bellroy." },

  /* ─────────────── Fashion / luxury ─────────────── */
  { url: "https://www.loewe.com", note: "Loewe." },
  { url: "https://www.bottegaveneta.com", note: "Bottega Veneta." },
  { url: "https://www.gucci.com", note: "Gucci." },
  { url: "https://www.prada.com", note: "Prada." },
  { url: "https://www.dior.com", note: "Dior." },
  { url: "https://www.chanel.com", note: "Chanel." },
  { url: "https://www.hermes.com", note: "Hermès." },
  { url: "https://www.ysl.com", note: "Saint Laurent." },
  { url: "https://www.balenciaga.com", note: "Balenciaga." },
  { url: "https://www.celine.com", note: "Celine." },
  { url: "https://www.jacquemus.com", note: "Jacquemus." },
  { url: "https://www.thefrankieshop.com", note: "Frankie Shop." },
  { url: "https://www.totokaelo.com", note: "Totokaelo (eh, may be defunct)." },
  { url: "https://www.tods.com", note: "Tod's." },
  { url: "https://www.armani.com", note: "Armani." },
  { url: "https://aldenshoe.com", note: "Alden." },
  { url: "https://www.cosstores.com", note: "COS." },
  { url: "https://www.arket.com", note: "Arket." },
  { url: "https://www.uniqlo.com", note: "Uniqlo." },
  { url: "https://www.theory.com", note: "Theory." },
  { url: "https://www.aritzia.com", note: "Aritzia." },
  { url: "https://www.sandro-paris.com", note: "Sandro Paris." },
  { url: "https://www.maje.com", note: "Maje." },
  { url: "https://www.amazon.com", note: "Amazon (control comparison)." },
  { url: "https://goyard.com", note: "Goyard." },

  /* ─────────────── Architecture / industrial / brand ─────────────── */
  { url: "https://big.dk", note: "Bjarke Ingels Group." },
  { url: "https://www.snohetta.com", note: "Snøhetta." },
  { url: "https://www.oma.com", note: "OMA." },
  { url: "https://studiogang.com", note: "Studio Gang." },
  { url: "https://www.mvrdv.nl", note: "MVRDV." },
  { url: "https://www.fosterandpartners.com", note: "Foster + Partners." },
  { url: "https://www.heatherwick.com", note: "Heatherwick Studio." },
  { url: "https://www.olsonkundig.com", note: "Olson Kundig." },
  { url: "https://www.kkaa.co.jp", note: "Kengo Kuma." },
  { url: "https://www.tadao-ando.com", note: "Tadao Ando." },
  { url: "https://www.zha.com", note: "Zaha Hadid Architects." },
  { url: "https://herzogdemeuron.com", note: "Herzog & de Meuron." },
  { url: "https://www.studiomumbai.com", note: "Studio Mumbai." },
  { url: "https://www.ahmm.co.uk", note: "AHMM." },
  { url: "https://www.officekgdvs.com", note: "OFFICE Kersten Geers David Van Severen." },
  { url: "https://www.kerrhill.com", note: "Kerr & Hill." },
  { url: "https://www.dyson.com", note: "Dyson (dup)." },
  { url: "https://www.teenageengineering.com", note: "Teenage Engineering." },
  { url: "https://www.muji.com", note: "MUJI." },
  { url: "https://www.apple.com", note: "Apple." },
  { url: "https://nothing.tech", note: "Nothing tech." },
  { url: "https://genelec.com", note: "Genelec." },
  { url: "https://shure.com", note: "Shure microphones." },
  { url: "https://www.sennheiser.com", note: "Sennheiser." },
  { url: "https://en-uk.sennheiser.com", note: "Sennheiser UK." },
  { url: "https://www.beyerdynamic.com", note: "Beyerdynamic." },
  { url: "https://www.ferrari.com", note: "Ferrari." },
  { url: "https://www.porsche.com", note: "Porsche." },
  { url: "https://www.mclaren.com", note: "McLaren." },
  { url: "https://www.tesla.com", note: "Tesla." },
  { url: "https://www.rivian.com", note: "Rivian." },
  { url: "https://www.lucidmotors.com", note: "Lucid Motors." },
  { url: "https://www.polestar.com", note: "Polestar." },
  { url: "https://www.lotuscars.com", note: "Lotus." },

  /* ─────────────── Food / hospitality / restaurants ─────────────── */
  { url: "https://noma.dk", note: "Noma." },
  { url: "https://www.elevenmadisonpark.com", note: "Eleven Madison Park." },
  { url: "https://atomixnyc.com", note: "Atomix." },
  { url: "https://eltulipan.com", note: "El Tulipán; eh." },
  { url: "https://cooking.nytimes.com", note: "NYT Cooking." },
  { url: "https://www.bonappetit.com", note: "Bon Appétit." },
  { url: "https://eater.com", note: "Eater." },
  { url: "https://www.seriouseats.com", note: "Serious Eats." },
  { url: "https://www.intelligentsiacoffee.com", note: "Intelligentsia Coffee." },
  { url: "https://bluebottlecoffee.com", note: "Blue Bottle Coffee." },
  { url: "https://stumptowncoffee.com", note: "Stumptown." },
  { url: "https://www.fellowproducts.com", note: "Fellow Products." },
  { url: "https://huckberry.com", note: "Huckberry; rugged." },
  { url: "https://www.standardhotels.com", note: "Standard Hotels." },
  { url: "https://www.ace-hotel.com", note: "Ace Hotel." },
  { url: "https://www.aman.com", note: "Aman Resorts." },
  { url: "https://www.sixsenses.com", note: "Six Senses." },
  { url: "https://www.airbnb.com", note: "Airbnb." },
  { url: "https://www.delta.com", note: "Delta." },
  { url: "https://united.com", note: "United." },

  /* ─────────────── Cultural institutions / museums / galleries ─────────────── */
  { url: "https://www.metmuseum.org", note: "The Met." },
  { url: "https://www.moma.org", note: "MoMA." },
  { url: "https://whitney.org", note: "Whitney." },
  { url: "https://www.tate.org.uk", note: "Tate." },
  { url: "https://www.vam.ac.uk", note: "V&A." },
  { url: "https://www.centrepompidou.fr", note: "Centre Pompidou." },
  { url: "https://www.louvre.fr", note: "Louvre." },
  { url: "https://www.rijksmuseum.nl", note: "Rijksmuseum." },
  { url: "https://www.stedelijk.nl", note: "Stedelijk." },
  { url: "https://walkerart.org", note: "Walker Art Center." },
  { url: "https://www.icaboston.org", note: "ICA Boston." },
  { url: "https://www.sfmoma.org", note: "SFMOMA." },
  { url: "https://www.lacma.org", note: "LACMA." },
  { url: "https://www.diaart.org", note: "Dia Art Foundation." },
  { url: "https://hammer.ucla.edu", note: "Hammer Museum." },
  { url: "https://www.brooklynmuseum.org", note: "Brooklyn Museum." },
  { url: "https://studiomuseum.org", note: "Studio Museum Harlem." },
  { url: "https://www.palaisdetokyo.com", note: "Palais de Tokyo." },
  { url: "https://www.gagosian.com", note: "Gagosian." },
  { url: "https://www.davidzwirner.com", note: "David Zwirner." },
  { url: "https://www.hauserwirth.com", note: "Hauser & Wirth." },
  { url: "https://www.pacegallery.com", note: "Pace Gallery." },
  { url: "https://whitecube.com", note: "White Cube." },
  { url: "https://www.lissongallery.com", note: "Lisson Gallery." },
  { url: "https://www.mplus.org.hk", note: "M+ Hong Kong." },
  { url: "https://www.mori.art.museum", note: "Mori Art Museum." },
  { url: "https://www.guggenheim.org", note: "Guggenheim." },
  { url: "https://www.smithsonianmag.com", note: "Smithsonian Magazine." },
  { url: "https://www.nga.gov", note: "National Gallery of Art." },

  /* ─────────────── Schools / education ─────────────── */
  { url: "https://www.yale.edu/sa", note: "Yale School of Art (eh)." },
  { url: "https://www.risd.edu", note: "RISD." },
  { url: "https://www.media.mit.edu", note: "MIT Media Lab." },
  { url: "https://www.bauhaus-dessau.de", note: "Bauhaus Dessau." },
  { url: "https://www.angewandte.at", note: "University of Applied Arts Vienna." },
  { url: "https://www.ecal.ch", note: "ECAL." },
  { url: "https://www.konstfack.se", note: "Konstfack." },
  { url: "https://werkplaatstypografie.org", note: "Werkplaats Typografie." },
  { url: "https://www.rca.ac.uk", note: "Royal College of Art." },
  { url: "https://www.arts.ac.uk", note: "UAL (Central Saint Martins)." },
  { url: "https://www.parsons.edu", note: "Parsons." },
  { url: "https://www.gold.ac.uk", note: "Goldsmiths." },
  { url: "https://www.beauxartsparis.fr", note: "Beaux-Arts Paris." },
  { url: "https://www.sciencespo.fr", note: "Sciences Po." },
  { url: "https://www.harvard.edu", note: "Harvard." },
  { url: "https://www.mit.edu", note: "MIT." },
  { url: "https://www.stanford.edu", note: "Stanford." },
  { url: "https://figma.com/config", note: "Figma Config." },
  { url: "https://www.offf.barcelona", note: "OFFF Festival." },
  { url: "https://www.commonpublishing.org", note: "Common Publishing (eh)." },

  /* ─────────────── Design tooling / templates / kits ─────────────── */
  { url: "https://www.framer.com/templates", note: "Framer templates." },
  { url: "https://store.cargo.site", note: "Cargo Site." },
  { url: "https://carrd.co", note: "Carrd." },
  { url: "https://www.squarespace.com", note: "Squarespace." },
  { url: "https://www.wix.com", note: "Wix." },
  { url: "https://webflow.com", note: "Webflow." },
  { url: "https://gumroad.com", note: "Gumroad." },
  { url: "https://www.lemonsqueezy.com", note: "Lemon Squeezy." },
  { url: "https://www.notion.so/templates", note: "Notion templates." },
  { url: "https://nextjs.org", note: "Next.js docs." },
  { url: "https://reactjs.org", note: "React docs." },
  { url: "https://svelte.dev", note: "Svelte." },
  { url: "https://kit.svelte.dev", note: "SvelteKit." },
  { url: "https://vuejs.org", note: "Vue." },
  { url: "https://nuxt.com", note: "Nuxt." },
  { url: "https://qwik.builder.io", note: "Qwik." },
  { url: "https://remix.run", note: "Remix." },
  { url: "https://docs.astro.build", note: "Astro docs." },
  { url: "https://astro.build", note: "Astro." },
  { url: "https://tailwindcss.com", note: "Tailwind CSS." },
  { url: "https://tailwindui.com", note: "Tailwind UI." },
  { url: "https://www.radix-ui.com", note: "Radix UI." },
  { url: "https://chakra-ui.com", note: "Chakra UI." },
  { url: "https://mantine.dev", note: "Mantine." },
  { url: "https://nextui.org", note: "NextUI." },
  { url: "https://daisyui.com", note: "DaisyUI." },
  { url: "https://www.headlessui.com", note: "Headless UI." },
  { url: "https://lucide.dev", note: "Lucide icons." },
  { url: "https://heroicons.com", note: "Heroicons." },
  { url: "https://feathericons.com", note: "Feather Icons." },
  { url: "https://phosphoricons.com", note: "Phosphor Icons." },
  { url: "https://thenounproject.com", note: "Noun Project." },
  { url: "https://www.iconfinder.com", note: "Iconfinder." },

  /* ─────────────── Web3 / crypto / DAOs ─────────────── */
  { url: "https://ethereum.org", note: "Ethereum." },
  { url: "https://www.uniswap.org", note: "Uniswap." },
  { url: "https://opensea.io", note: "OpenSea." },
  { url: "https://www.arweave.org", note: "Arweave." },
  { url: "https://www.helium.com", note: "Helium." },
  { url: "https://www.rainbow.me", note: "Rainbow wallet." },
  { url: "https://zora.co", note: "Zora." },
  { url: "https://highlight.xyz", note: "Highlight (Web3)." },
  { url: "https://farcaster.xyz", note: "Farcaster." },

  /* ─────────────── Communications / social ─────────────── */
  { url: "https://discord.com", note: "Discord." },
  { url: "https://signal.org", note: "Signal." },
  { url: "https://telegram.org", note: "Telegram." },
  { url: "https://mastodon.social", note: "Mastodon." },
  { url: "https://bsky.app", note: "Bluesky." },
  { url: "https://x.com", note: "X (formerly Twitter)." },
  { url: "https://www.linkedin.com", note: "LinkedIn." },
  { url: "https://substack.com", note: "Substack." },
  { url: "https://buttondown.email", note: "Buttondown newsletters." },
  { url: "https://convertkit.com", note: "ConvertKit." },
  { url: "https://beehiiv.com", note: "beehiiv." },
  { url: "https://ghost.org", note: "Ghost." },
  { url: "https://hey.com", note: "Hey email." },
  { url: "https://superhuman.com", note: "Superhuman." },
  { url: "https://www.shortwave.com", note: "Shortwave email." },
  { url: "https://missiveapp.com", note: "Missive." },

  /* ─────────────── Climate / mission / impact ─────────────── */
  { url: "https://watershed.com", note: "Watershed." },
  { url: "https://patch.io", note: "Patch carbon." },
  { url: "https://www.climeworks.com", note: "Climeworks." },
  { url: "https://stripe.com/climate", note: "Stripe Climate." },
  { url: "https://www.frontierclimate.com", note: "Frontier." },
  { url: "https://www.effectivealtruism.org", note: "EA." },
  { url: "https://www.gatesnotes.com", note: "Gates Notes." },
  { url: "https://wellcomecollection.org", note: "Wellcome Collection." },

  /* ─────────────── Health / wellness ─────────────── */
  { url: "https://www.calm.com", note: "Calm." },
  { url: "https://www.headspace.com", note: "Headspace." },
  { url: "https://www.oura.com", note: "Oura ring." },
  { url: "https://www.whoop.com", note: "WHOOP." },
  { url: "https://www.peloton.com", note: "Peloton." },
  { url: "https://www.strava.com", note: "Strava." },
  { url: "https://www.fitbod.me", note: "Fitbod." },
  { url: "https://www.hims.com", note: "Hims." },
  { url: "https://www.forhers.com", note: "Hers." },
  { url: "https://ro.co", note: "Ro." },

  /* ─────────────── Productivity / personal sites / niche tools ─────────────── */
  { url: "https://www.todoist.com", note: "Todoist." },
  { url: "https://obsidian.md", note: "Obsidian." },
  { url: "https://logseq.com", note: "Logseq." },
  { url: "https://reflect.app", note: "Reflect (dup)." },
  { url: "https://capacities.io", note: "Capacities." },
  { url: "https://anytype.io", note: "Anytype." },
  { url: "https://www.bear.app", note: "Bear writer." },
  { url: "https://ulysses.app", note: "Ulysses." },
  { url: "https://soulver.app", note: "Soulver." },
  { url: "https://thingsapp.com", note: "Things app." },
  { url: "https://structured.app", note: "Structured." },
  { url: "https://amie.so", note: "Amie calendar." },
  { url: "https://cron.com", note: "Cron calendar." },
  { url: "https://www.notion.so", note: "Notion main." },
  { url: "https://www.tana.inc", note: "Tana (dup)." },

  /* ─────────────── Open source projects with strong sites ─────────────── */
  { url: "https://nodejs.org", note: "Node.js." },
  { url: "https://bun.sh", note: "Bun (alt)." },
  { url: "https://www.rust-lang.org", note: "Rust." },
  { url: "https://go.dev", note: "Go language." },
  { url: "https://elixir-lang.org", note: "Elixir." },
  { url: "https://www.postgresql.org", note: "PostgreSQL." },
  { url: "https://redis.io", note: "Redis." },
  { url: "https://www.mongodb.com", note: "MongoDB." },
  { url: "https://www.docker.com", note: "Docker." },
  { url: "https://kubernetes.io", note: "Kubernetes." },
  { url: "https://prometheus.io", note: "Prometheus." },
  { url: "https://grafana.com", note: "Grafana (dup)." },
  { url: "https://temporal.io", note: "Temporal." },
  { url: "https://www.confluent.io", note: "Confluent." },
  { url: "https://kafka.apache.org", note: "Apache Kafka." },
  { url: "https://github.com", note: "GitHub." },
  { url: "https://about.gitlab.com", note: "GitLab." },
  { url: "https://bitbucket.org/product", note: "Bitbucket." },
  { url: "https://sourcehut.org", note: "Sourcehut." },
  { url: "https://stackoverflow.com", note: "Stack Overflow." },

  /* ─────────────── Niche / experimental ─────────────── */
  { url: "https://aslice.com", note: "Aslice DJ split." },
  { url: "https://teenageengineering.com", note: "Teenage Engineering (dup)." },
  { url: "https://generative.fm", note: "Generative.fm." },
  { url: "https://patatap.com", note: "Patatap." },
  { url: "https://ciid.dk", note: "CIID." },
  { url: "https://bunny.studio", note: "Bunny Studio." },
  { url: "https://www.dropbox.com/design", note: "Dropbox Design." },
  { url: "https://www.airbnb.design", note: "Airbnb Design." },
  { url: "https://stripe.com/press", note: "Stripe Press." },
  { url: "https://design.facebook.com", note: "Meta Design." },
  { url: "https://material.io", note: "Material Design." },
  { url: "https://primer.style", note: "GitHub Primer." },
  { url: "https://atlassian.design", note: "Atlassian Design System." },
  { url: "https://polaris.shopify.com", note: "Shopify Polaris." },
  { url: "https://www.lightningdesignsystem.com", note: "Salesforce Lightning." },
  { url: "https://gov.uk/design-system", note: "GOV.UK Design System." },

  /* ─────────────── Photography / arts / illustrators ─────────────── */
  { url: "https://www.magnumphotos.com", note: "Magnum Photos." },
  { url: "https://www.flickr.com", note: "Flickr." },
  { url: "https://unsplash.com", note: "Unsplash." },
  { url: "https://stocksy.com", note: "Stocksy." },
  { url: "https://www.500px.com", note: "500px." },
  { url: "https://www.gettyimages.com", note: "Getty." },
  { url: "https://www.trentparke.com", note: "Trent Parke photo." },
  { url: "https://www.alecsoth.com", note: "Alec Soth." },
  { url: "https://kelseydake.com", note: "Kelsey Dake illustrator." },
  { url: "https://www.geoffmcfetridge.com", note: "Geoff McFetridge." },
  { url: "https://malikafavre.com", note: "Malika Favre." },
  { url: "https://www.lottereiniger.com", note: "Lotte Reiniger (eh)." },

  /* ─────────────── Conference / event / community sites ─────────────── */
  { url: "https://config.figma.com", note: "Figma Config." },
  { url: "https://www.offf.barcelona", note: "OFFF (dup)." },
  { url: "https://thedesignconference.com.au", note: "The Design Conference AU." },
  { url: "https://www.pancakescon.com", note: "PancakesCon (eh)." },
  { url: "https://reactsummit.com", note: "React Summit." },
  { url: "https://www.cssday.nl", note: "CSS Day." },

  /* ─────────────── Personal blogs / writing ─────────────── */
  { url: "https://stratechery.com", note: "Stratechery." },
  { url: "https://www.derekbruff.org", note: "Derek Bruff." },
  { url: "https://www.gwern.net", note: "Gwern." },
  { url: "https://www.lesswrong.com", note: "LessWrong." },
  { url: "https://slatestarcodex.com", note: "Slate Star Codex." },
  { url: "https://astralcodexten.com", note: "Astral Codex Ten." },
  { url: "https://putanumonit.com", note: "Putanumonit." },
  { url: "https://www.ribbonfarm.com", note: "Ribbonfarm." },
  { url: "https://nadiaaaa.medium.com", note: "Nadia Asparouhova (eh check)." },
  { url: "https://www.julian.com", note: "Julian Shapiro (dup)." },

  /* ─────────────── Travel / hospitality / outdoors ─────────────── */
  { url: "https://www.eurostar.com", note: "Eurostar." },
  { url: "https://www.airfrance.com", note: "Air France." },
  { url: "https://www.ana.co.jp", note: "ANA." },
  { url: "https://www.expedia.com", note: "Expedia." },
  { url: "https://www.hipmunk.com", note: "Hipmunk (eh, defunct?)." },
  { url: "https://www.hopper.com", note: "Hopper." },
  { url: "https://www.kayak.com", note: "Kayak." },
  { url: "https://www.skyscanner.net", note: "Skyscanner." },
  { url: "https://outdoorvoices.com", note: "OV (dup)." },
  { url: "https://www.rei.com", note: "REI." },
  { url: "https://www.huckberry.com", note: "Huckberry (dup)." },
  { url: "https://www.mountainhardwear.com", note: "Mountain Hardwear." },
  { url: "https://www.thenorthface.com", note: "The North Face." },
  { url: "https://columbia.com", note: "Columbia." },

  /* ─────────────── Indie / personal / hidden gems ─────────────── */
  { url: "https://sandymaguire.me", note: "Sandy Maguire." },
  { url: "https://blog.cmpxchg8b.com", note: "cmpxchg8b." },
  { url: "https://drewdevault.com", note: "Drew DeVault." },
  { url: "https://briankung.dev", note: "Brian Kung." },
  { url: "https://daniel.org", note: "Daniel.org (eh)." },
  { url: "https://hacker-news.firebaseio.com", note: "HN (eh)." },
  { url: "https://news.ycombinator.com", note: "Hacker News." },
  { url: "https://www.metafilter.com", note: "Metafilter." },
  { url: "https://lobste.rs", note: "Lobsters." },
  { url: "https://www.tildes.net", note: "Tildes." },
  { url: "https://www.hackerrank.com", note: "HackerRank." },
  { url: "https://www.kaggle.com", note: "Kaggle." },
  { url: "https://leetcode.com", note: "LeetCode." },
  { url: "https://codepen.io", note: "CodePen." },
  { url: "https://codesandbox.io", note: "CodeSandbox." },
  { url: "https://stackblitz.com", note: "StackBlitz." },
  { url: "https://glitch.com", note: "Glitch." },
  { url: "https://replit.com", note: "Replit." },

  /* ─────────────── More agencies international ─────────────── */
  { url: "https://www.formafantasma.com", note: "Formafantasma." },
  { url: "https://amistudio.com", note: "Ami Studio." },
  { url: "https://www.linkedbyair.net", note: "Linked by Air." },
  { url: "https://www.bratus.com", note: "Bratus agency." },
  { url: "https://www.coucou.studio", note: "Coucou Studio." },
  { url: "https://www.studio-takeuma.com", note: "Studio Takeuma." },
  { url: "https://www.studio-takt.com", note: "Studio Takt." },

  /* ─────────────── Misc: shopify themes / portfolios / hidden ─────────────── */
  { url: "https://gumroad.com/blog", note: "Gumroad blog (eh)." },
  { url: "https://blog.figma.com", note: "Figma blog." },
  { url: "https://stripe.press", note: "Stripe Press main." },
  { url: "https://everlaw.com", note: "Everlaw." },
  { url: "https://retool.com", note: "Retool." },
  { url: "https://userpilot.com", note: "Userpilot." },
  { url: "https://www.pendo.io", note: "Pendo." },
  { url: "https://www.statsig.com", note: "Statsig." },
  { url: "https://www.amplitude.com", note: "Amplitude." },
  { url: "https://mixpanel.com", note: "Mixpanel." },
  { url: "https://heap.io", note: "Heap." },
  { url: "https://www.fullstory.com", note: "FullStory." },
  { url: "https://www.hotjar.com", note: "Hotjar." },
  { url: "https://maze.co", note: "Maze." },
  { url: "https://www.usertesting.com", note: "UserTesting." },
  { url: "https://typeform.com", note: "Typeform." },
  { url: "https://tally.so", note: "Tally forms." },
  { url: "https://www.calendly.com", note: "Calendly." },
  { url: "https://savvycal.com", note: "SavvyCal." },
  { url: "https://www.docusign.com", note: "DocuSign." },
  { url: "https://www.hellosign.com", note: "HelloSign." },

  /* ─── Phase 5 top-up: under-represented categories ─── */

  // Designer / developer portfolios
  { url: "https://lukestewart.dev", note: "Luke Stewart." },
  { url: "https://nathangraule.com", note: "Nathan Graule." },
  { url: "https://www.bencurnow.com", note: "Ben Curnow." },
  { url: "https://shadymousa.com", note: "Shady Moussa." },
  { url: "https://andjelkomilojevic.com", note: "Andjelko Milojevic." },
  { url: "https://ymo.studio", note: "Y/M/O studio." },
  { url: "https://chez.studio", note: "Chez studio." },
  { url: "https://lukasgrebner.com", note: "Lukas Grebner." },
  { url: "https://romaintrystram.com", note: "Romain Trystram illustrator." },
  { url: "https://timrodenbroker.com", note: "Tim Rodenbröker creative coding." },
  { url: "https://www.lukehaas.me", note: "Luke Haas." },
  { url: "https://benadam.me", note: "Ben Adam." },
  { url: "https://saulhardman.com", note: "Saul Hardman." },
  { url: "https://www.cassie.codes", note: "Cassie Evans." },
  { url: "https://amelia.wattenberger.com", note: "Amelia Wattenberger." },
  { url: "https://wattenberger.com", note: "Amelia Wattenberger long-form." },
  { url: "https://ciechanow.ski", note: "Bartosz Ciechanowski explainer." },
  { url: "https://kentcdodds.com", note: "Kent C. Dodds." },
  { url: "https://nicoloribaudo.it", note: "Nicolò Ribaudo." },
  { url: "https://lihbr.com", note: "Lihbr." },
  { url: "https://hmpl-lang.dev", note: "Hypermedia ML." },
  { url: "https://andy-bell.co.uk", note: "Andy Bell personal." },
  { url: "https://www.matuzo.at", note: "Manuel Matuzović." },
  { url: "https://artemis.run", note: "Artemis run." },
  { url: "https://stuffmadehere.com", note: "Stuff Made Here." },
  { url: "https://www.alex.do", note: "Alex." },
  { url: "https://wojtekgaczynski.com", note: "Wojtek Gaczynski." },
  { url: "https://andriiponomarov.com", note: "Andrii Ponomarov." },
  { url: "https://amitm.com", note: "Amit Merchant." },
  { url: "https://martin-bednorz.com", note: "Martin Bednorz." },
  { url: "https://thalia.studio", note: "Thalia studio." },
  { url: "https://niklas.studio", note: "Niklas studio." },
  { url: "https://jasper.cool", note: "Jasper Cool." },
  { url: "https://orpetron.com", note: "Orpetron design awards." },
  { url: "https://stage.so", note: "Stage portfolio platform." },
  { url: "https://flexile.co", note: "Flexile." },
  { url: "https://www.blakeir.com", note: "Blake Ir." },
  { url: "https://hertzy.studio", note: "Hertzy studio." },
  { url: "https://nick.scialli.me", note: "Nick Scialli." },
  { url: "https://lewishorne.com", note: "Lewis Horne." },

  // Type foundries (additional)
  { url: "https://www.swisstypefaces.com", note: "Swiss Typefaces." },
  { url: "https://www.cstm.berlin", note: "CSTM Berlin." },
  { url: "https://camelot-typefaces.com", note: "Camelot Typefaces." },
  { url: "https://www.philsfonts.com", note: "Phil's Fonts." },
  { url: "https://typearture.com", note: "Type Arture." },
  { url: "https://www.fenotype.com", note: "Fenotype." },
  { url: "https://www.justanotherfoundry.com", note: "Just Another Foundry." },
  { url: "https://klimtypefoundry.com", note: "Klim alt." },
  { url: "https://wolfdesign.com", note: "Wolf Design." },
  { url: "https://degarism.com", note: "Degarism Studio." },
  { url: "https://www.mass-driver.com", note: "Mass Driver." },
  { url: "https://www.pampatype.com", note: "Pampa Type." },
  { url: "https://newglyph.com", note: "New Glyph." },
  { url: "https://blanc.life", note: "Blanc foundry." },

  // Cultural institutions / museums
  { url: "https://www.lacollection.io", note: "LaCollection NFT museum." },
  { url: "https://www.serpentinegalleries.org", note: "Serpentine Galleries." },
  { url: "https://www.barbican.org.uk", note: "Barbican." },
  { url: "https://designmuseum.org", note: "Design Museum London." },
  { url: "https://www.cooperhewitt.org", note: "Cooper Hewitt." },
  { url: "https://www.macba.cat", note: "MACBA Barcelona." },
  { url: "https://www.macba.org", note: "MACBA org." },
  { url: "https://www.wro.art.pl", note: "WRO Art Center." },
  { url: "https://www.fondationlouisvuitton.fr", note: "Fondation Louis Vuitton." },
  { url: "https://museum.wales", note: "National Museum Wales." },
  { url: "https://www.thejewishmuseum.org", note: "Jewish Museum NYC." },
  { url: "https://newmuseum.org", note: "New Museum." },
  { url: "https://www.madmuseum.org", note: "MAD Museum." },
  { url: "https://www.peabodyessex.org", note: "Peabody Essex." },
  { url: "https://www.icamiami.org", note: "ICA Miami." },
  { url: "https://www.cornellbotanicgardens.org", note: "Cornell Botanic." },
  { url: "https://thefastandtheslow.com", note: "Fast and Slow." },
  { url: "https://cima.nyc", note: "CIMA NYC." },
  { url: "https://www.huyghe.com", note: "Huyghe." },

  // Photographers / illustrators / artists
  { url: "https://emiliereynolds.com", note: "Emilie Reynolds photo." },
  { url: "https://wolfgangtillmans.com", note: "Wolfgang Tillmans." },
  { url: "https://kennygrant.com", note: "Kenny Grant photo." },
  { url: "https://www.pieterhugo.com", note: "Pieter Hugo." },
  { url: "https://www.ryanmcginleystudios.com", note: "Ryan McGinley." },
  { url: "https://nadavkander.com", note: "Nadav Kander." },
  { url: "https://www.ruvenafanador.com", note: "Ruven Afanador." },
  { url: "https://andersborgersen.com", note: "Anders Borgersen." },
  { url: "https://taishimoto.com", note: "Tai Shimoto." },
  { url: "https://gregorycoyes.com", note: "Gregory Coyes." },
  { url: "https://maxsiedentopf.com", note: "Max Siedentopf." },
  { url: "https://www.geoffmcfetridge.com", note: "Geoff McFetridge." },
  { url: "https://malikafavre.com", note: "Malika Favre illustration." },
  { url: "https://www.olliestudio.co.uk", note: "Ollie Studio illustration." },
  { url: "https://oliverjeffers.com", note: "Oliver Jeffers." },
  { url: "https://www.erikjohanssonphoto.com", note: "Erik Johansson." },
  { url: "https://annielibovitz.com", note: "Annie Leibovitz." },
  { url: "https://www.platonphoto.com", note: "Platon photo." },
  { url: "https://timflach.com", note: "Tim Flach." },

  // Hospitality / hotels
  { url: "https://www.aman.com", note: "Aman Resorts (dup)." },
  { url: "https://hoshinoresorts.com", note: "Hoshino Resorts." },
  { url: "https://www.parkhyatt.com", note: "Park Hyatt." },
  { url: "https://www.shinta-mani.com", note: "Shinta Mani." },
  { url: "https://www.belmond.com", note: "Belmond." },
  { url: "https://www.locke.com", note: "Locke hotels." },
  { url: "https://www.standardhotels.com", note: "Standard Hotels (dup)." },
  { url: "https://lasourceresort.com", note: "La Source resort." },
  { url: "https://lyfehotels.com", note: "Lyfe hotels." },
  { url: "https://hotelbycommunesf.com", note: "Hotel by Commune SF." },
  { url: "https://www.dolderhotel.com", note: "Dolder Grand." },

  // Restaurants / food
  { url: "https://www.atelier-crenn.com", note: "Atelier Crenn." },
  { url: "https://danieldlc.com", note: "Daniel NYC." },
  { url: "https://leberndardin.com", note: "Le Bernardin." },
  { url: "https://www.dinnerbyheston.com", note: "Dinner by Heston." },
  { url: "https://www.mirazur.fr", note: "Mirazur." },
  { url: "https://www.ditta.com", note: "Ditta café." },
  { url: "https://wagamama.com", note: "Wagamama." },
  { url: "https://www.shake-shack.com", note: "Shake Shack." },
  { url: "https://chickfila.com", note: "Chick-fil-A." },
  { url: "https://www.dominos.com", note: "Domino's." },
  { url: "https://www.chipotle.com", note: "Chipotle." },
  { url: "https://www.eataly.com", note: "Eataly." },
  { url: "https://www.deathandcompany.com", note: "Death and Co." },
  { url: "https://attaboybar.com", note: "Attaboy bar." },

  // Fashion / luxury (additional)
  { url: "https://www.miumiu.com", note: "Miu Miu." },
  { url: "https://www.versace.com", note: "Versace." },
  { url: "https://www.fendi.com", note: "Fendi." },
  { url: "https://www.givenchy.com", note: "Givenchy." },
  { url: "https://www.valentino.com", note: "Valentino." },
  { url: "https://www.tomford.com", note: "Tom Ford." },
  { url: "https://www.toryburch.com", note: "Tory Burch." },
  { url: "https://www.coach.com", note: "Coach." },
  { url: "https://www.maisonmargiela.com", note: "Maison Margiela." },
  { url: "https://www.marni.com", note: "Marni." },
  { url: "https://www.balmain.com", note: "Balmain." },
  { url: "https://www.berluti.com", note: "Berluti." },
  { url: "https://www.smythson.com", note: "Smythson." },
  { url: "https://www.brunellocucinelli.com", note: "Brunello Cucinelli." },
  { url: "https://www.officineuniversellebuly.com", note: "Officine Universelle Buly." },
  { url: "https://www.cdg-tradingmuseum.com", note: "CdG Trading Museum." },
  { url: "https://issey-miyake-online.com", note: "Issey Miyake online." },
  { url: "https://www.chloe.com", note: "Chloé." },
  { url: "https://www.karenwalker.com", note: "Karen Walker." },
  { url: "https://www.maisonkitsune.com", note: "Maison Kitsuné." },

  // Industrial / brand / car
  { url: "https://www.bmwgroup.com", note: "BMW Group." },
  { url: "https://www.audi.com", note: "Audi." },
  { url: "https://www.mercedes-benz.com", note: "Mercedes-Benz." },
  { url: "https://www.lamborghini.com", note: "Lamborghini." },
  { url: "https://www.bugatti.com", note: "Bugatti." },
  { url: "https://www.aston-martin.com", note: "Aston Martin." },
  { url: "https://www.alpinecars.com", note: "Alpine Cars." },
  { url: "https://www.koenigsegg.com", note: "Koenigsegg." },
  { url: "https://www.maserati.com", note: "Maserati." },
  { url: "https://www.peakdesign.com", note: "Peak Design (dup)." },
  { url: "https://www.dyson.com/lifestyle", note: "Dyson Lifestyle." },
  { url: "https://www.lego.com", note: "LEGO." },
  { url: "https://www.muji.com/jp", note: "MUJI Japan." },
  { url: "https://www.nintendo.com", note: "Nintendo." },
  { url: "https://www.playstation.com", note: "PlayStation." },
  { url: "https://www.xbox.com", note: "Xbox." },
  { url: "https://www.minimal.so", note: "Minimal so." },
  { url: "https://www.minimalist.com", note: "Minimalist." },

  // Music labels / cinema
  { url: "https://thirdmanrecords.com", note: "Third Man Records." },
  { url: "https://daptonerecords.com", note: "Daptone Records." },
  { url: "https://hyperdub.net", note: "Hyperdub." },
  { url: "https://www.mexicansummer.com", note: "Mexican Summer." },
  { url: "https://constellationrecords.com", note: "Constellation." },
  { url: "https://thrilljockey.com", note: "Thrill Jockey." },
  { url: "https://www.dragcity.com", note: "Drag City." },
  { url: "https://merge-records.bandcamp.com", note: "Merge Records." },
  { url: "https://www.bbcearth.com", note: "BBC Earth." },
  { url: "https://www.studioghibli.com", note: "Studio Ghibli." },
  { url: "https://wescraven.com", note: "Wes Craven." },
  { url: "https://wesandersonworld.com", note: "Wes Anderson world." },

  // Web design / awards / showcase
  { url: "https://oneshade.com", note: "One Shade." },
  { url: "https://www.themeforest.net", note: "ThemeForest." },
  { url: "https://www.creativeapplications.net", note: "Creative Applications." },
  { url: "https://designernews.co", note: "Designer News." },
  { url: "https://www.commonlounge.com", note: "Common Lounge." },
  { url: "https://lookback.com", note: "Lookback." },
  { url: "https://reactdigest.net", note: "React Digest." },
  { url: "https://patternpad.com", note: "Pattern Pad." },

  // Misc product / SaaS / startup
  { url: "https://shopify.com", note: "Shopify." },
  { url: "https://www.gusto.com", note: "Gusto HR." },
  { url: "https://justworks.com", note: "Justworks." },
  { url: "https://rippling.com", note: "Rippling." },
  { url: "https://deel.com", note: "Deel." },
  { url: "https://remote.com", note: "Remote.com." },
  { url: "https://www.ashbyhq.com", note: "Ashby HQ." },
  { url: "https://greenhouse.io", note: "Greenhouse." },
  { url: "https://www.lever.co", note: "Lever." },
  { url: "https://www.workable.com", note: "Workable." },
  { url: "https://www.bamboohr.com", note: "BambooHR." },
  { url: "https://www.workday.com", note: "Workday." },
  { url: "https://www.salesforce.com", note: "Salesforce." },
  { url: "https://www.hubspot.com", note: "HubSpot." },
  { url: "https://www.zendesk.com", note: "Zendesk." },
  { url: "https://intercom.com", note: "Intercom." },
  { url: "https://www.zoom.com", note: "Zoom." },
  { url: "https://www.cluely.com", note: "Cluely." },
  { url: "https://www.dovetail.com", note: "Dovetail." },
  { url: "https://miro.com", note: "Miro." },
  { url: "https://mural.co", note: "Mural." },
  { url: "https://www.notbilt.com", note: "Not Built." },
  { url: "https://www.crisp.chat", note: "Crisp chat." },
  { url: "https://www.formstack.com", note: "Formstack." },
  { url: "https://stackshare.io", note: "StackShare." },
  { url: "https://www.statuspage.io", note: "Statuspage." },
  { url: "https://kanban.com", note: "Kanban." },
  { url: "https://basecamp.com", note: "Basecamp." },
  { url: "https://hey.com", note: "Hey email (dup)." },
  { url: "https://thoughtbot.com", note: "Thoughtbot." },

  // Open source / communities / OSS
  { url: "https://www.electronjs.org", note: "Electron." },
  { url: "https://nx.dev", note: "Nx." },
  { url: "https://turbo.build", note: "Turbo." },
  { url: "https://vite.dev", note: "Vite." },
  { url: "https://parceljs.org", note: "Parcel." },
  { url: "https://esbuild.github.io", note: "esbuild." },
  { url: "https://webpack.js.org", note: "Webpack." },
  { url: "https://rollupjs.org", note: "Rollup." },
  { url: "https://prettier.io", note: "Prettier." },
  { url: "https://eslint.org", note: "ESLint." },
  { url: "https://www.typescriptlang.org", note: "TypeScript." },
  { url: "https://flow.org", note: "Flow." },
  { url: "https://www.prisma.io", note: "Prisma." },
  { url: "https://orm.drizzle.team", note: "Drizzle ORM." },
  { url: "https://kysely.dev", note: "Kysely." },
  { url: "https://trpc.io", note: "tRPC." },
  { url: "https://hono.dev", note: "Hono." },
  { url: "https://elysiajs.com", note: "Elysia." },
  { url: "https://fastify.dev", note: "Fastify." },
  { url: "https://expressjs.com", note: "Express." },
  { url: "https://nestjs.com", note: "NestJS." },
  { url: "https://docs.nestjs.com", note: "NestJS docs." },
  { url: "https://tanstack.com", note: "TanStack." },
  { url: "https://zod.dev", note: "Zod." },
  { url: "https://valibot.dev", note: "Valibot." },
  { url: "https://www.npmjs.com", note: "npm." },
  { url: "https://yarnpkg.com", note: "Yarn." },
  { url: "https://pnpm.io", note: "pnpm." },

  /* ─── Top-up to 1000: high-confidence brand surfaces ─── */

  // Apple subdomains + product surfaces
  { url: "https://www.apple.com/iphone", note: "Apple iPhone." },
  { url: "https://www.apple.com/macbook-pro", note: "Apple MBP." },
  { url: "https://www.apple.com/ipad", note: "Apple iPad." },
  { url: "https://www.apple.com/watch", note: "Apple Watch." },
  { url: "https://www.apple.com/airpods", note: "Apple AirPods." },
  { url: "https://www.apple.com/vision", note: "Apple Vision Pro." },
  { url: "https://developer.apple.com", note: "Apple Developer." },
  { url: "https://www.apple.com/airtag", note: "Apple AirTag." },
  { url: "https://www.apple.com/homepod", note: "Apple HomePod." },

  // Google product surfaces
  { url: "https://about.google", note: "About Google." },
  { url: "https://blog.google", note: "Google Blog." },
  { url: "https://design.google", note: "Google Design." },
  { url: "https://aboutme.google", note: "Google About Me." },
  { url: "https://www.google.com/chromebook", note: "Chromebook." },
  { url: "https://store.google.com", note: "Google Store." },
  { url: "https://gemini.google.com", note: "Gemini." },
  { url: "https://workspace.google.com", note: "Google Workspace." },

  // Microsoft + OSS
  { url: "https://www.microsoft.com", note: "Microsoft." },
  { url: "https://copilot.microsoft.com", note: "Copilot." },
  { url: "https://www.surface.com", note: "Microsoft Surface." },
  { url: "https://github.blog", note: "GitHub Blog." },
  { url: "https://github.com/explore", note: "GitHub Explore." },
  { url: "https://opensource.com", note: "Opensource.com." },

  // Adobe + creative tools
  { url: "https://www.adobe.com", note: "Adobe." },
  { url: "https://www.adobe.com/creativecloud.html", note: "Adobe Creative Cloud." },
  { url: "https://www.adobe.com/products/photoshop.html", note: "Photoshop." },
  { url: "https://www.adobe.com/products/illustrator.html", note: "Illustrator." },
  { url: "https://express.adobe.com", note: "Adobe Express." },
  { url: "https://www.canva.com", note: "Canva." },
  { url: "https://www.figma.com/templates", note: "Figma Templates." },
  { url: "https://www.framer.com/templates", note: "Framer Templates (dup)." },

  // Social media platforms (design-forward landing pages)
  { url: "https://about.instagram.com", note: "Instagram About." },
  { url: "https://about.facebook.com", note: "Facebook About." },
  { url: "https://about.tiktok.com", note: "TikTok About." },
  { url: "https://creators.spotify.com", note: "Spotify for Creators." },
  { url: "https://www.spotify.com/us/premium", note: "Spotify Premium." },

  // Streaming + media
  { url: "https://www.disneyplus.com", note: "Disney+." },
  { url: "https://www.hbomax.com", note: "HBO Max." },
  { url: "https://tv.youtube.com", note: "YouTube TV." },
  { url: "https://music.youtube.com", note: "YouTube Music." },
  { url: "https://www.crunchyroll.com", note: "Crunchyroll." },
  { url: "https://www.criterion.com/current", note: "Criterion Current." },
  { url: "https://www.imdb.com", note: "IMDb." },
  { url: "https://www.rottentomatoes.com", note: "Rotten Tomatoes." },
  { url: "https://www.lettboxd.com", note: "Letterboxd (eh)." },
  { url: "https://letterboxd.com", note: "Letterboxd." },

  // News / journalism
  { url: "https://www.nytimes.com", note: "NYT." },
  { url: "https://www.washingtonpost.com", note: "WaPo." },
  { url: "https://www.theguardian.com", note: "The Guardian." },
  { url: "https://www.economist.com", note: "The Economist." },
  { url: "https://www.bloomberg.com", note: "Bloomberg." },
  { url: "https://www.ft.com", note: "Financial Times." },
  { url: "https://www.wsj.com", note: "WSJ." },
  { url: "https://www.reuters.com", note: "Reuters." },
  { url: "https://www.bbc.com", note: "BBC News." },
  { url: "https://www.npr.org", note: "NPR." },
  { url: "https://www.theintercept.com", note: "The Intercept." },
  { url: "https://www.propublica.org", note: "ProPublica." },
  { url: "https://www.businessinsider.com", note: "Business Insider." },
  { url: "https://www.cnbc.com", note: "CNBC." },

  // Sports / lifestyle media
  { url: "https://www.nba.com", note: "NBA." },
  { url: "https://www.nfl.com", note: "NFL." },
  { url: "https://www.nike.com", note: "Nike." },
  { url: "https://www.adidas.com", note: "Adidas." },
  { url: "https://www.newbalance.com", note: "New Balance." },
  { url: "https://www.puma.com", note: "Puma." },
  { url: "https://www.underarmour.com", note: "Under Armour." },
  { url: "https://www.gymshark.com", note: "Gymshark." },
  { url: "https://www.alo-yoga.com", note: "Alo Yoga." },
  { url: "https://www.aloyoga.com", note: "Alo Yoga (alt)." },
  { url: "https://www.lululemon.com", note: "Lululemon." },

  // E-commerce platforms / marketplaces
  { url: "https://www.etsy.com", note: "Etsy." },
  { url: "https://www.depop.com", note: "Depop." },
  { url: "https://www.grailed.com", note: "Grailed." },
  { url: "https://www.therealreal.com", note: "The RealReal." },
  { url: "https://www.farfetch.com", note: "Farfetch." },
  { url: "https://www.zalando.com", note: "Zalando." },
  { url: "https://www.poshmark.com", note: "Poshmark." },

  // Tech companies / SaaS we missed
  { url: "https://www.dropbox.com", note: "Dropbox." },
  { url: "https://www.box.com", note: "Box." },
  { url: "https://www.dropbox.com/business", note: "Dropbox Business." },
  { url: "https://www.evernote.com", note: "Evernote." },
  { url: "https://www.getpocket.com", note: "Pocket." },
  { url: "https://www.feedly.com", note: "Feedly." },
  { url: "https://www.flipboard.com", note: "Flipboard." },
  { url: "https://medium.com", note: "Medium." },

  // Specific design-forward SaaS landing pages
  { url: "https://stripe.com/atlas", note: "Stripe Atlas." },
  { url: "https://stripe.com/connect", note: "Stripe Connect." },
  { url: "https://stripe.com/billing", note: "Stripe Billing." },
  { url: "https://stripe.com/identity", note: "Stripe Identity." },
  { url: "https://www.dropbox.com/dash", note: "Dropbox Dash." },
  { url: "https://www.shopify.com/uk", note: "Shopify UK." },

  // Travel
  { url: "https://www.airbnb.com/host", note: "Airbnb Host." },
  { url: "https://www.airbnb.com/luxe", note: "Airbnb Luxe." },
  { url: "https://www.uber.com", note: "Uber." },
  { url: "https://www.lyft.com", note: "Lyft." },
  { url: "https://www.lime.com", note: "Lime." },
  { url: "https://www.bird.co", note: "Bird." },
  { url: "https://www.doordash.com", note: "DoorDash." },
  { url: "https://www.grubhub.com", note: "Grubhub." },
  { url: "https://www.postmates.com", note: "Postmates." },
  { url: "https://www.deliveroo.com", note: "Deliveroo." },
  { url: "https://www.justeat.com", note: "Just Eat." },
  { url: "https://www.gopuff.com", note: "GoPuff." },

  // Music / audio (additional)
  { url: "https://www.spotify.com", note: "Spotify (root dup)." },
  { url: "https://www.apple.com/apple-music", note: "Apple Music landing (dup)." },
  { url: "https://www.tidal.com/business", note: "Tidal Business." },
  { url: "https://www.audius.co", note: "Audius." },
  { url: "https://www.beatport.com", note: "Beatport." },
  { url: "https://www.bandcamp.com/feed", note: "Bandcamp Feed." },
  { url: "https://www.last.fm", note: "Last.fm." },

  // Games / entertainment
  { url: "https://store.steampowered.com", note: "Steam." },
  { url: "https://www.epicgames.com", note: "Epic Games." },
  { url: "https://www.gog.com", note: "GOG." },
  { url: "https://www.itch.io", note: "Itch.io." },
  { url: "https://www.twitch.tv", note: "Twitch." },
  { url: "https://discord.com/nitro", note: "Discord Nitro." },

  // Web platforms / hosting / domains
  { url: "https://www.namecheap.com", note: "Namecheap." },
  { url: "https://www.godaddy.com", note: "GoDaddy." },
  { url: "https://domains.google", note: "Google Domains." },
  { url: "https://www.netlify.com", note: "Netlify." },
  { url: "https://surge.sh", note: "Surge." },
  { url: "https://www.heroku.com", note: "Heroku." },
  { url: "https://www.digitalocean.com", note: "DigitalOcean." },
  { url: "https://www.linode.com", note: "Linode." },
  { url: "https://aws.amazon.com", note: "AWS." },
  { url: "https://azure.microsoft.com", note: "Azure." },
  { url: "https://cloud.google.com", note: "Google Cloud." },

  // Productivity tools
  { url: "https://www.atlassian.com", note: "Atlassian." },
  { url: "https://trello.com", note: "Trello." },
  { url: "https://asana.com", note: "Asana." },
  { url: "https://monday.com", note: "Monday." },
  { url: "https://www.clickup.com", note: "ClickUp." },
  { url: "https://www.smartsheet.com", note: "Smartsheet." },
  { url: "https://airtable.com", note: "Airtable." },
  { url: "https://www.coda.io", note: "Coda." },

  // AI / specific products
  { url: "https://chat.openai.com", note: "ChatGPT (web)." },
  { url: "https://www.perplexity.ai/comet", note: "Perplexity Comet." },
  { url: "https://x.ai", note: "xAI." },
  { url: "https://grok.com", note: "Grok." },
  { url: "https://kagi.com", note: "Kagi." },
  { url: "https://www.you.com", note: "You.com." },
  { url: "https://www.poe.com", note: "Poe." },
  { url: "https://playht.com", note: "Play.ht." },
  { url: "https://www.descript.com/podcast", note: "Descript Podcast." },
  { url: "https://www.suno.com/about", note: "Suno About." },
  { url: "https://leonardo.ai", note: "Leonardo." },
  { url: "https://www.recraft.ai", note: "Recraft." },
  { url: "https://www.opal.so", note: "Opal." },

  // Dev tools we missed
  { url: "https://nx.app", note: "Nx Cloud." },
  { url: "https://moonrepo.dev", note: "Moon repo." },
  { url: "https://lerna.js.org", note: "Lerna." },
  { url: "https://www.changesets.dev", note: "Changesets." },
  { url: "https://semaphoreci.com", note: "Semaphore CI." },
  { url: "https://circleci.com", note: "CircleCI." },
  { url: "https://www.travis-ci.com", note: "Travis CI." },
  { url: "https://buildkite.com", note: "Buildkite." },
  { url: "https://www.buildbot.net", note: "Buildbot." },
  { url: "https://www.gitkraken.com", note: "GitKraken." },
  { url: "https://www.tower.app", note: "Tower." },
  { url: "https://www.git-tower.com", note: "Git Tower (alt)." },
  { url: "https://desktop.github.com", note: "GitHub Desktop." },
  { url: "https://www.sourcetreeapp.com", note: "SourceTree." },
  { url: "https://www.charlesproxy.com", note: "Charles Proxy." },
  { url: "https://insomnia.rest", note: "Insomnia." },
  { url: "https://www.postman.com", note: "Postman." },
  { url: "https://hoppscotch.io", note: "Hoppscotch." },
  { url: "https://www.bruno.com", note: "Bruno API." },

  // Design + UI products
  { url: "https://uizard.io", note: "Uizard." },
  { url: "https://www.proto.io", note: "Proto.io." },
  { url: "https://principle.design", note: "Principle (Mac)." },
  { url: "https://playbookux.com", note: "Playbook UX." },
  { url: "https://looka.com", note: "Looka." },
  { url: "https://www.brandcrowd.com", note: "BrandCrowd." },
  { url: "https://www.canva.com/pro", note: "Canva Pro." },

  // Health + medtech with strong landing
  { url: "https://www.viome.com", note: "Viome." },
  { url: "https://www.modernhealth.com", note: "Modern Health." },
  { url: "https://www.gingerlabs.com", note: "Ginger Labs." },
  { url: "https://www.tempo.fit", note: "Tempo." },
  { url: "https://www.tonal.com", note: "Tonal." },
  { url: "https://www.mirror.co", note: "Mirror." },
  { url: "https://www.appliedmiami.com", note: "Applied Miami." },
  { url: "https://www.functionhealth.com", note: "Function Health." },

  // Climate / energy / mission
  { url: "https://www.tesla.com/solar-panels", note: "Tesla Solar." },
  { url: "https://www.tesla.com/megapack", note: "Tesla Megapack." },
  { url: "https://www.heliogen.com", note: "Heliogen." },
  { url: "https://www.commonwealthfusion.com", note: "Commonwealth Fusion." },
  { url: "https://kohofin.com", note: "KOHO." },
  { url: "https://www.ecologi.com", note: "Ecologi." },

  // Education / learning
  { url: "https://www.duolingo.com", note: "Duolingo." },
  { url: "https://www.babbel.com", note: "Babbel." },
  { url: "https://www.brilliant.org", note: "Brilliant." },
  { url: "https://www.khanacademy.org", note: "Khan Academy." },
  { url: "https://www.codecademy.com", note: "Codecademy." },
  { url: "https://www.coursera.org", note: "Coursera." },
  { url: "https://www.edx.org", note: "edX." },
  { url: "https://www.udemy.com", note: "Udemy." },
  { url: "https://www.pluralsight.com", note: "Pluralsight." },
  { url: "https://www.skillshare.com", note: "Skillshare." },
  { url: "https://www.masterclass.com", note: "MasterClass." },
];

if (seedUrls.length < 700) {
  console.warn(
    `[seed-urls] only ${seedUrls.length} URLs, expected 700+ post-Phase-3.5. Re-check the file.`,
  );
}
